### ISSUE TITLE
VM2 SEL274

### ISSUE THREAD

**Issue by xolod79** [1801BM1/cpu11#17]
When the VIRQ request does not acknowledge the interrupt vector, interrupts should occur at address SEL274, but the usual interrupt 004 occurs. Analysis of the problem showed that the reason is that the pli_ack signal is one clock cycle behind p[6] = acin & qbto & iako.
![SEL274](https://github.com/1801BM1/cpu11/assets/39098890/86722a2d-3b7e-40c6-8a9d-1a2ef60a12f1)
It seems that this happened when switching to a synchronous processor model. This is not a problem at the DVK and UKNC, but it is critical for the work of the Souyz Neon.
I made a workaround by delaying the end of the wbi_stb_o signal by one clock cycle, but I’m not sure that this is the best solution.

```
+reg   old_wbi_stb_o;

always @(posedge vm_clk_p)
begin
+  old_wbi_stb_o <= wbi_stb_o;
-   vec_stb <= wbi_stb_o & ~wbi_una_o; 
+  vec_stb <= (wbi_stb_o | (old_wbi_stb_o & ~wbi_stb_o )) & ~wbi_una_o;
```

**Comment by 1801BM1** [comment]
Thank you for the comprehensive issue description, will handle.

**Comment by 1801BM1** [comment]
The fix pushed: https://github.com/1801BM1/cpu11/commit/2f765b4f632b3d9ce43a556e5d36b53776963bea

**Comment by xolod79** [comment]
I checked it on FPGAs Soyuz Neone, it works fine.

**Comment by 1801BM1** [comment]
> I checked it on FPGAs Soyuz Neone, it works fine.

OK, thank you
