### ISSUE TITLE
Minor syntax fix VM2 PREFETCH

### ISSUE THREAD

**Issue by xolod79** [1801BM1/cpu11#19]
I think we need to change blocking to non blocking statements.
```
-       bir_fix = (breg[14:12] != 3'o0)    // two ops instructions
+       bir_fix <= (breg[14:12] != 3'o0)    // two ops instructions
```

In these places:
https://github.com/1801BM1/cpu11/blob/abe8b682a7de38f89865fcd4f57d9ba4d6d2256c/vm2/hdl/org/rtl/vm2_qbus.v#L1031
https://github.com/1801BM1/cpu11/blob/abe8b682a7de38f89865fcd4f57d9ba4d6d2256c/vm2/hdl/syn/rtl/vm2_qbus.v#L1025
https://github.com/1801BM1/cpu11/blob/abe8b682a7de38f89865fcd4f57d9ba4d6d2256c/vm2/hdl/wbc/rtl/vm2_wb.v#L730

**Comment by xolod79** [comment]
Do you have any objection to this commit?

**Comment by 1801BM1** [comment]
> Do you have any objection to this commit?

There is no any objections :)
https://github.com/1801BM1/cpu11/commit/48be491dfcc1dfe9deb11f9ab4c74d43213f46ac

Thank you for the reporting
